// This file is automatically generated by tools.
// To update all exports inside project
// run :
// genexp

export 'app_localizations.dart';
export 'app_localizations_en.dart';
export 'app_localizations_id.dart';
export 'localizations.exports.dart';
