// This file is automatically generated by tools.
// To update all exports inside project
// run :
// genexp

export 'dependencies.dart';
export 'localizations/localizations.exports.dart';
export 'main.dart';
export 'movies.dart';
export 'src/src.exports.dart';
