// This file is automatically generated by tools.
// To update all exports inside project
// run :
// genexp

export 'main/main.exports.dart';
export 'movie-detail.dart';
export 'movie-list.dart';
export 'pages.exports.dart';
